language: python
python:
        - "3.5"

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
        - eval "${MATRIX_EVAL}"
        
install:
  - pip install -r requirements-dev.txt

script:
        - python setup.py test
